nginx:
    build: ./images/nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - ./conf/sites-enabled:/etc/nginx/conf.d
      - ./volumes/logs/nginx:/var/log/nginx
      - ~/work:/opt
    env_file:
      - .env

php:
    build: ./images/php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "redis"
      - "memcache"
    volumes:
      - ~/work:/opt
    working_dir: /opt
    env_file:
      - .env

mysql:
   build: ./images/mysql
   ports:
     - "3306:3306"
   volumes:
      - ./volumes/data/mysql:/var/lib/mysql
   env_file:
     - .env

redis:
   build: ./images/redis
   ports:
     - "6379:6379"
mongo:
   build: ./images/mongo
   ports:
     - "27017:27017"

memcache:
   build: ./images/memcache
   ports:
     - "11211:11211"

elasticsearch:
   build: ./images/elasticsearch
   ports:
     - "9200:9200"
     - "9300:9300"
