nginx:
  build: images/nginx
  ports:
    - "80:80"
  links:
    - php:php
  volumes:
    - ./conf/sites-enabled:/etc/nginx/conf.d
    - ./volumes/logs/nginx:/var/log/nginx
    - ~/work:/opt
  env_file: .env

php:
  build: images/php
  ports:
    - "9000:9000"
    - "9001:9001"
    - "3000:8080"
  volumes:
    - ~/work:/opt
  working_dir: /opt
  env_file: .env

php7:
  build: images/php7
  ports:
    - "9007:9000"
    - "9008:9001"
  volumes:
    - ~/work:/opt
  working_dir: /opt
  env_file: .env

node:
  build: images/node
  volumes:
    - ~/work:/opt
  ports:
    - "8080:8080"
  working_dir: /opt
  env_file: .env

memcache:
  build: images/memcache
  ports:
    - "11211:11211"

mysql:
  build: images/mysql
  ports:
    - "3306:3306"
  volumes:
    - ./volumes/data/mysql:/var/lib/mysql
  env_file: .env

mongo:
  build: images/mongo
  ports:
    - "27017:27017"

ssdb:
  build: images/ssdb
  ports:
    - "16379:16379"
  env_file: .env

redis:
  build: images/redis
  ports:
    - "6379:6379"

solr:
  build: images/solr
  ports:
    - "8983:8983"

elasticsearch:
  build: images/elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"

# banyandb:
#   build: images/banyandb
#   volumes:
#     - ~/work:/opt
#   ports:
#     - "1026:1026"
#   working_dir: /opt
#   env_file: .env
