nginx:
    build: images/nginx
    ports:
        - "80:80"
    links:
        - "php"
    volumes:
        - ./conf/sites-enabled:/etc/nginx/conf.d
        - ./volumes/logs/nginx:/var/log/nginx
        - ~/work:/opt
    env_file: .env
php:
    build: images/php
    ports:
        - "9000:9000"
        - "9001:9001"
    links:
<<<<<<< HEAD
        - "memcache"
        - "mysql"
=======
      - "mysql"
      - "memcache"
      - "node"
>>>>>>> 030b797bcd48ca74a5ec1c04e95c91a01a496486
    volumes:
        - ~/work:/opt
    working_dir: /opt
<<<<<<< HEAD
    env_file: .env
memcache:
    build: images/memcache
    ports:
        - "11211:11211"
mysql:
    build: images/mysql
    ports:
        - "3306:3306"
    volumes:
        - ./volumes/data/mysql:/var/lib/mysql
    env_file: .env
mongo:
    build: images/mongo
    ports:
        - "27017:27017"
ssdb:
    build: images/ssdb
    ports:
        - "8899:8899"
    volumes:
        - ./volumes/data/ssdb:/var/lib/ssdb
    env_file: .env
# node:
#     build: images/node
#     ports:
#         - "8001:8001"
#     volumes:
#         - ~/work:/opt
#     working_dir: /opt
# redis:
#    build: images/redis
#    ports:
#      - "6379:6379"
# elasticsearch:
#    build: images/elasticsearch
=======
    env_file:
      - .env

node:
   build: ./images/node
   volumes:
     - ~/work:/opt
   working_dir: /opt
   env_file:
     - .env

mysql:
   build: ./images/mysql
   ports:
     - "3306:3306"
   volumes:
      - ./volumes/data/mysql:/var/lib/mysql
   env_file:
     - .env

mongo:
   build: ./images/mongo
   ports:
     - "27017:27017"

memcache:
   build: ./images/memcache
   ports:
     - "11211:11211"

# redis:
#    build: ./images/redis
#    ports:
#      - "6379:6379"
#
# elasticsearch:
#    build: ./images/elasticsearch
>>>>>>> 030b797bcd48ca74a5ec1c04e95c91a01a496486
#    ports:
#      - "9200:9200"
#      - "9300:9300"
