#!/usr/bin/env bash

#more see https://github.com/michalmatoga/phpstorm-docker-interpreter

# 初始化docker
eval $(docker-machine env default)

# 如果images不存在就构建
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [[ "$(docker images -q dobe_php5)" == "" ]]; then
    docker build -t dobe_php5 ${DIR}/../images/php5/
fi

# 如果同名的容器存在就删除
CMD=$(docker ps | grep 'phpunit' | awk "{print \$1}")
[ "" != "${CMD}" ] && docker rm -f ${CMD}

# 容器内执行php
docker run -i --rm --net=host -w "${PWD}" -v "${PWD}":"${PWD}" -v "/private":"/private" \
--name="phpunit" dobe_php5 php -d include_path=/root/.composer/vendor/phpunit/phpunit "$@"
